package com.example.tugas3praktikum;

import java.util.ArrayList;

public class DataSource {
    public static ArrayList<Data> datas = generateDummyDatas();

    private static ArrayList<Data> generateDummyDatas(){
        ArrayList<Data> datas = new ArrayList<>();
        datas.add(new Data(R.drawable.ppmcd,R.drawable.mcd,"mcdonals","McDonald's offers a diverse menu featuring classic favorites like the Big Mac and Chicken McNuggets, alongside healthier options like salads and grilled chicken sandwiches. With convenient locations and quick service, it's a popular choice for a satisfying meal on the go.","337","127"));
        datas.add(new Data(R.drawable.ppkfc,R.drawable.kfc,"kfc","KFC is a popular fast-food chain known for its signature fried chicken. With a menu that includes a variety of chicken options such as original recipe, extra crispy, and grilled chicken, KFC caters to different tastes. In addition to chicken, they offer sides like mashed potatoes, coleslaw, and biscuits. KFC's convenient locations and quick service make it a go-to choice for those craving delicious fried chicken and classic comfort food.","477","938"));
        datas.add(new Data(R.drawable.pppizza,R.drawable.pizza,"pizzahutindonesia","Pizza Hut menawarkan beragam pizza lezat serta hidangan lain seperti pasta dan sayap ayam. Dengan suasana yang nyaman dan pelayanan cepat, Pizza Hut menjadi pilihan favorit untuk menikmati makanan cepat saji yang lezat.","23","636"));
        datas.add(new Data(R.drawable.ppstarbuk,R.drawable.starbuk,"starbucks","Starbucks is a popular coffeehouse chain known for its wide variety of coffee drinks, including espresso, lattes, and frappuccinos. In addition to coffee, Starbucks also offers tea, pastries, and light snacks. With cozy atmospheres and convenient locations, Starbucks is a go-to destination for coffee lovers seeking a quick caffeine fix or a place to relax and unwind.","534","655"));
        datas.add(new Data(R.drawable.ppwendys,R.drawable.wendys,"wendys","Wendy's is a well-known fast-food chain famous for its square-shaped burgers and fresh, never frozen beef. Alongside burgers, Wendy's offers a variety of salads, chicken sandwiches, and sides like fries and chili. With its commitment to quality ingredients and fast service, Wendy's is a popular choice for those craving delicious and satisfying fast food.","244","177"));
        datas.add(new Data(R.drawable.ppdunkin,R.drawable.dunkin,"dunkindounatid","Dunkin' Donuts adalah merek internasional yang terkenal dengan donatnya yang lezat. Donat mereka memiliki berbagai macam varian, mulai dari donat berlapis gula, donat berisi krim atau selai, hingga donat yang dihiasi dengan berbagai topping seperti cokelat, kacang, atau glazur. Selain donat, Dunkin' Donuts juga menyajikan kopi dan minuman lainnya. Donat mereka terkenal karena rasa yang lezat dan tekstur yang lembut, menjadikannya pilihan favorit untuk camilan atau sarapan cepat.","573","936"));
        datas.add(new Data(R.drawable.ppdomino,R.drawable.domino,"dominopizzaidn","Domino's Pizza adalah waralaba pizza global yang terkenal dengan pizza cepat saji berkualitas. Mereka menawarkan berbagai macam pizza, dari klasik seperti Pepperoni hingga unik seperti BBQ Chicken. Layanan pengiriman yang cepat dan efisien membuat Domino's menjadi pilihan populer untuk makan malam santai atau acara bersama teman dan keluarga.","836","654"));
        datas.add((new Data(R.drawable.ppomaha,R.drawable.omaha,"omahaoffcial","Steak adalah hidangan daging panggang yang lezat. Dipanggang di atas api terbuka atau dalam oven, steak memiliki cita rasa kaya dan tekstur lembut. Sering disajikan dengan saus dan pendamping seperti kentang goreng atau salad. Populer di restoran mewah atau di rumah untuk makan malam istimewa.","112","319")));
        datas.add(new Data(R.drawable.ppcola,R.drawable.cola,"cocacolareal","Coca-Cola is a globally renowned carbonated soft drink. It's known for its refreshing taste and iconic branding. With its secret recipe dating back to the late 19th century, Coca-Cola has become one of the most popular beverages worldwide. It's enjoyed in various settings, from casual gatherings to formal events, and is often paired with meals or enjoyed on its own.","738","109"));
        datas.add(new Data(R.drawable.ppikea,R.drawable.ikea,"ikeaswedia","IKEA Mat är en del av det globala möbelvarumärket IKEA. IKEA Mat erbjuder ett brett utbud av svenska och internationella rätter i IKEA-butiker över hela världen. Menyn inkluderar rätter som köttbullar, lax, varmkorv, soppa och olika bakverk. IKEA Mat är känt för sin prisvärda kvalitet och erbjuder en bekväm matupplevelse för IKEA-besökare före eller efter shoppingen.","27","11"));
        return datas;
    }
}
